### ISSUE TITLE
로고, 슬라이드 이미지를 추가합니다. 

### ISSUE THREAD

**Issue by daamable** [team-durumi/didkorea#1]
<img width="467" alt="slide1" src="https://user-images.githubusercontent.com/39326928/77411790-50085480-6e00-11ea-8628-955f64f6d7e8.png">
<img width="465" alt="slide2" src="https://user-images.githubusercontent.com/39326928/77411798-526aae80-6e00-11ea-9ae4-b591de030f17.png">

<img width="168" alt="logo" src="https://user-images.githubusercontent.com/39326928/77412347-1b48cd00-6e01-11ea-88da-a20ef1e676cd.png">

[드라이브 링크](https://drive.google.com/drive/u/2/folders/1s8rcb5dJAO1L8REgWeVEPGv43WJqQTvT)

**Comment by sunparty** [comment]
@daamable 님 로고 이미지 위에 흰색 선이 있는거랑 스펠링이 틀린게 있어서 새로좀 부탁드립니다.

**Comment by daamable** [comment]
선 있능거 새로 올릴게요 스펠링은 gwangmyung 말고 kwangmyung으로 해주세요

**Comment by daamable** [comment]
아 코포레이션이 틀렸구나요 네 다시 올릴게요

**Comment by sunparty** [comment]
@daamable  선 없이 바탕화면 하나로만 해주세요!! 이미지 상단에 흰색 선이 있어요 자세히 보면

**Comment by daamable** [comment]
그럴게요 제가 7시까지 올릴게요

**Comment by daamable** [comment]
변경했습니다. 확인 부탁드려요. 
로고는 좀 어색하면 그냥 이미지말고 화면에 텍스트로 넣고 박스 정도 넣으면 어떨까 해요.
