### ISSUE TITLE
아웃룩 메일 연동 실패?

### ISSUE THREAD

**Issue by daamable** [team-durumi/didkorea#10]
3.31 
- mir9 메일호스팅(mail.didkorea.co.kr)으로 연동되어있던 아웃룩에 최신 메일이 연동되지 않기 시작함
- cloudflare에 운짱이 추가했던 레코드가 mir9 거였고, 여기서 제대로 이전해주지 않음을 확인 
- inames 문의 결과 메일서버 비용만 지급되어있고, 연결은 되어있지 않아 네임서버에 레코드를 추가하면 된다고 알려줌(오늘 아침) 

<img width="783" alt="스크린샷 2020-04-01 오전 11 19 12" src="https://user-images.githubusercontent.com/39326928/78092414-aed65b00-740a-11ea-94cc-dc496b94eb5e.png">

- didkorea@didkorea.co.kr 메일이 유지되어야 하므로, 어제 g suite 를 추가함(cloudflare 통해)

<img width="1053" alt="스크린샷 2020-04-01 오전 11 18 47" src="https://user-images.githubusercontent.com/39326928/78092408-a9791080-740a-11ea-831d-c083232c8c28.png">

- gmail 연동은 잘됨 
- g suite와 아웃룩 연동에 실패 (이해가 안감...)
- 사장님은 아웃룩밖에 안 써봐서 지메일은 도저히 못쓰시겠다고....
- 아웃룩 연동 전문가(?)(콤비엔컴 홍현찬)과 소통 중 
- 전문가가 말하길, 연동 실패 이유는 cloudflare?

(계속 정리할게요)

**Comment by mozodev** [comment]
위에 올려주신 레코드는 기존 메일 서버를 버리고 g suite 서버로 메일을 받고, 보내는 상황인데 이게 원하는게 맞나요? 어차피 대표님이 아웃룩을 쓰신다고 하면 메일은 하드에 있으니까 보내고 받기만 하면 되는데...

1. 아이네임즈 메일 vs  g suite 메일
어떤 것을 사용하시려 하는건지 결정 필요..
둘 다 돈 내는거고 가격이 큰 차이가 없으면 g suite가 좋죠.. 
그럼 아이네임즈 서비스는 해지...

2. 현재 g suite로 메일서버가 설정되어 있으니 이대로 계속 사용하려면 
대표님 아웃룩 서버 설정에서 로그인 아이디 비번을 g suite에서 추가한 사용자 계정 비번으로
변경해야 접근이 됩니다. 이게 안되서 메일 확인이 안되시는 듯..

**Comment by daamable** [comment]
네 g suite로 하고자 하는게 맞아요.

**Comment by daamable** [comment]
Gmail 계정으로 아웃룩 로그인을 했는데 이름 비번이 올바르지 않는다는 오류가 계속 뜨네요 ㅠ

**Comment by mozodev** [comment]
그럼 대표님 사용하시는 컴퓨터의 아웃룩 프로그램 설정에서 smtp 서버, 아이디, 비번을 g suite 계정으로 수정하셔야 메일 그대로 사용할 수 있어요... 아마 직접 방문하셔야할 듯 ㅎ

그리고 지금 확인해보니 didkorea.co.kr A 레코드를 아이네임즈 서버로 누군가 할당해 놓아서 홈페이지가 아니라 웹메일 로그인 화면으로 연결되고 있는데 이건 제가 바로잡겠습니다. ㅎ

**Comment by woonjjang** [comment]
전화로 얘기했던 것을 정리해 보면

1. G suite 메일로 수신이 잘 된다고 합니다. didkorea@didkorea.co.kr 로 발송하면 웹에서 메일 수신 확인은 잘 됨.
2. IMAP 설정이 켜졌는지 확인 : [링크보기](https://pdi-mz-support.zendesk.com/hc/ko/articles/360029103612--Gmail-%EC%95%84%EC%9B%83%EB%A3%A9-Outlook-2013-2016-%EC%97%90-%EC%A7%80%EB%A9%94%EC%9D%BC-Gmail-%EC%97%B0%EB%8F%99%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-IMAP-)
3. 담이 맥에 아웃룩 클라이언트 설치해서 같은 계정으로 접근해 보는 방법 (대표님 컴퓨터 프로그램 문제가 있을 수도 있어요.)

**Comment by mozodev** [comment]
다른 사업자가 메일 서버 및 DNS 가져가는 것으로 종결..
