### ISSUE TITLE
GraphQL을 이용해서 제품소개 페이지의 요소를 추상화.

### ISSUE THREAD

**Issue by sunparty** [team-durumi/didkorea#11]
GraphQL과 data/series/series.yml을 이용해서 제품소개 중간에 들어가는 섭타이틀을 추상화 하여 고객이 직접 series.yml 에 기입을 하면 반영되도록 한다. (현재는 static 으로 박혀있고 subtitle 은 주석처리되어있음) 

(가령 01 Standard Roller Chain의 경우 
subtitle: "Worldwide standard chains complying with JIS and ANSI")

**Comment by mozodev** [comment]
- [ ] develop 브랜치 만들고 시도한 코드 커밋하고 푸시!

**Comment by sunparty** [comment]
![Screenshot 2020-04-01 at 3 29 58 PM](https://user-images.githubusercontent.com/7371023/78106139-be1ad000-742d-11ea-960c-f43e81592940.png)

**Comment by sunparty** [comment]
![Screenshot 2020-04-01 at 3 30 18 PM](https://user-images.githubusercontent.com/7371023/78106156-c83cce80-742d-11ea-9f2d-45d464ffe811.png)
