### ISSUE TITLE
메인페이지 <-> 회사소개 

### ISSUE THREAD

**Issue by daamable** [team-durumi/didkorea#12]
페이지 위치를 조정해주시면 어떨까 합니다. 

- 현재 메인 페이지에는 제품 소개가 나오는데, 메인페이지에 회사소개 화면이 나오게 한다. 
- 현재 메뉴 1 은 [회사소개(/about)인데, 이를 제품소개(/product)로 바꾸고 현재 메인페이지가 나오게 한다. 

요것 부탁드려도 될까요?

**Comment by daamable** [comment]
현재 didkorea.co.kr로 접근하면 바로 /about으로 다이렉션이 되네요. ㅠㅠㅠ
- didkorea.co.kr로 접근하면 /about(회사소개)의 내용이 나온다. url은 didkorea.co.kr로 한다.
- 원래 didkorea.co.kr 접근 시 나오던 제품소개를 1뎁스 첫번째 메뉴로 하고, url은 /product로 한다. 
이 부분 한번 더 봐주실 수 있을까요?

**Comment by sunparty** [comment]
전화상으로 요청하신대로 원래대로 원복! 닫습니다
