### ISSUE TITLE
푸터 이메일에 mailto 하이퍼링크를 추가한다. 

### ISSUE THREAD

**Issue by daamable** [team-durumi/didkorea#13]
푸터 이메일에 하이퍼링크 <a href="mailto:didkorea@didkorea.co.kr">didkorea@didkorea.co.kr</a> 를 추가한다. 

- 모조님 작업 https://github.com/team-durumi/didkorea/commit/e82e468a0644405e2c3b65bc72b3bf75d01eff9b 

요걸로 다 반영은 안된거지요?

**Comment by sunparty** [comment]
컴퓨터 브라우저에서 작동이 잘 안되는거 같아 노가다로 처리했고 하는김에 전화번호링크도 추가해씁니다.
