### ISSUE TITLE
[Production] 서비스 가입 및 아이디 / 비번 전달 / 배포 / 도메인 연결

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/didkorea#5]
1. 도메인 구매 및 관리 : 아이네임즈
2. 네임서버 및 IP수정 : https://www.cloudflare.com/
3. 서버대신 사용하는 서비스 : netlify.com

클라우드 플레어랑 넷리파이 담이 계정 만들어서 @sunparty  에게 전달해주세요. (didkorea 계정으로 만들어도 됩니다.)
두루미 계정에서 분리해서 전달해 드릴께요.

**Comment by daamable** [comment]
netlify와 cloudflare 모두 계정 만들었습니다. 계정 id는 동일합니다. 
> daamable@gmail.com

**Comment by daamable** [comment]
금주 내 이슈 : 도메인을 연결합니다. (didkorea.co.kr)

**Comment by woonjjang** [comment]
netlify 배포 완료 https://didkorea-real.netlify.com/

**Comment by woonjjang** [comment]
## Inames 
- 도메인 연장만 하는 곳으로 생각하면 됩니다. 
- 그룹웨어를 변경하거나, 혹은 현재 도메인을 활용해 서브도메인을 변경하거나 홈페이지를 변경할 때 이제 Cloudflare 에서 변경 및 확인함. (아래 이미지는 Cloudflare 네임서버로 변경<- 미르나인)
<img width="819" alt="스크린샷 2020-03-30 오전 11 31 37" src="https://user-images.githubusercontent.com/6022883/77869978-2c6b6100-727b-11ea-84de-dfdcd83a5d75.png">

## CloudFlare
- 예를 들어 inquiry.didkorea.co.kr 라는 서브도메인 요청이 들어오면 다른 서버 혹은 서비스로 포워딩해 줄 수 있음.
- A record 추가 및 관리를 할 수 있음. 
- 공격을 많이 받는 사이트의 네임서버 firewall을 유료로 사용해서 서버 트래픽을 줄여줄 수 있음. (이 사이트는 그럴일이 없을 듯)
- Analytics도 도움이 됨. 

## Netlify
- 이메일로 로그인 한 이후에 Add를 해서 명령어로 /public 빌드가 가능한 서비스를 배포하는데 사용한다. 
- Gatsby 프로젝트란 것을 파악하고 Repository만 연결, 명령어 Gatsby build 웹에 공개되는 /public 폴더만 잘 지정하면 된다. 
- Custom 도메인 연결시 보통 CNAME만 처리하면 되는데, 안 되는 경우에는 NETLIFY 로드밸런스 IP를 찍어주라고 나와 있음. 
- https://didkorea-real.netlify.com/
<img width="795" alt="스크린샷 2020-03-30 오전 11 49 15" src="https://user-images.githubusercontent.com/6022883/77870505-8c163c00-727c-11ea-8c85-64de37f096db.png">

## 마지막 Cloudflare에서
- 미르나인을 바라보던 IP를 Netlify로 변경한다.

**Comment by mozodev** [comment]
.com 도메인을 사시면 cloudflare에 카드 넣어놓고 이전해서 자동연장할 수 있습니다. .kr 등 한국도메인은 아직 지원하지 않아서 이전할 수 없습니다. ㅎ

**Comment by woonjjang** [comment]
@daamable @sunparty 혹시라도 재복구 하거나 이슈 있을 때 요 내용 참고해서 변경하세요.
