### ISSUE TITLE
파비콘을 수정해보세요.

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/didkorea#8]
- 배포하고 나니 보이네요 ^^

**Comment by daamable** [comment]
https://github.com/team-durumi/didkorea/commit/78680054e929367bb257c24ac7009fbb9edb0ae3 이렇게 하는게 맞는건지요?

**Comment by daamable** [comment]
https://github.com/team-durumi/didkorea/commit/6e90b435e38b0db8ecebeccfd464ffbaa97bf342 파비콘 업데이트 했는데 왜 안나오는지 확인 좀 한번 해주실 수 있을까요? ㅠㅠ
